## Copyright 2023 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI Windows GPU Workflow

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

### BUILD JOBS ###

  dpcpp-release-build:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true
      runs-on: '["Windows", "build"]'
      env-from-files: .github/workflows/dpcpp-release.env
      level-zero-version: public/1.12.0 # for ispcrt
      cmd: |
        $env:SYCL_BUNDLE_ROOT = $env:DPCPP_ROOT
        # disable warnings which lead to excessively large log files
        $env:CXXFLAGS = '-w'
        $env:CFLAGS = '-w'
        scripts\build\win.ps1 -G Ninja -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DBUILD_GPU_SUPPORT=ON -DBUILD_OIDN=ON
      artifact-out: build-windows-dpcpp-release
      artifact-path: build/install/ospray build/CMakeCache.txt build/ospray/build/CMakeCache.txt

  dpcpp-nightly-build:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true
      runs-on: '["Windows", "build"]'
      env-from-files: .github/workflows/dpcpp-nightly.env
      level-zero-version: public/1.12.0 # for ispcrt
      cmd: |
        $env:SYCL_BUNDLE_ROOT = $env:DPCPP_ROOT
        # disable warnings which lead to excessively large log files
        $env:CXXFLAGS = '-w'
        $env:CFLAGS = '-w'
        scripts\build\win.ps1 -G Ninja -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DBUILD_GPU_SUPPORT=ON -DBUILD_OIDN=ON
      artifact-out: build-windows-dpcpp-nightly
      artifact-path: build/install/ospray build/CMakeCache.txt build/ospray/build/CMakeCache.txt

  icx-release-build:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true
      runs-on: '["Windows", "build"]'
      env-from-files: .github/workflows/icx-win-release.env
      level-zero-version: public/1.12.0 # for ispcrt
      cmd: |
        # disable warnings which lead to excessively large log files
        $env:CXXFLAGS = '-w'
        $env:CFLAGS = '-w'
        scripts\build\win.ps1 -G Ninja -DCMAKE_CXX_COMPILER=icx -DCMAKE_C_COMPILER=icx -DBUILD_GPU_SUPPORT=ON -DBUILD_OIDN=ON -DBUILD_EMBREE_FROM_SOURCE=ON
      artifact-out: build-windows-icx-release
      artifact-path: build/install/ospray build/CMakeCache.txt build/ospray/build/CMakeCache.txt



### TEST JOBS ###

  dpcpp-release-test:
    needs: dpcpp-release-build
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true
      runs-on: '["Windows", "dg2"]'
      env-from-files: .github/workflows/dpcpp-release.env .github/workflows/gfx-windows-release.env
      cmd: |
        $env:SYCL_BUNDLE_ROOT = $env:DPCPP_ROOT
        $env:Path += ";$env:GITHUB_WORKSPACE\build\install\ospray\bin"
        scripts\tests\run_gpu_tests.ps1 "$env:GITHUB_WORKSPACE"
      artifact-in: build-windows-dpcpp-release
      artifact-out: test-windows-dpcpp-release
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true

  dpcpp-nightly-test:
    needs: dpcpp-nightly-build
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true
      runs-on: '["Windows", "dg2"]'
      env-from-files: .github/workflows/dpcpp-release.env .github/workflows/gfx-windows-release.env
      cmd: |
        $env:SYCL_BUNDLE_ROOT = $env:DPCPP_ROOT
        $env:Path += ";$env:GITHUB_WORKSPACE\build\install\ospray\bin"
        scripts\tests\run_gpu_tests.ps1 "$env:GITHUB_WORKSPACE"
      artifact-in: build-windows-dpcpp-nightly
      artifact-out: test-windows-dpcpp-nightly
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true

  icx-release-test:
    needs: icx-release-build
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true
      runs-on: '["Windows", "dg2"]'
      env-from-files: .github/workflows/icx-win-release.env .github/workflows/gfx-windows-release.env
      cmd: |
        $env:SYCL_BUNDLE_ROOT = $env:DPCPP_ROOT
        $env:Path += ";$env:GITHUB_WORKSPACE\build\install\ospray\bin"
        scripts\tests\run_gpu_tests.ps1 "$env:GITHUB_WORKSPACE"
      artifact-in: build-windows-icx-release
      artifact-out: test-windows-icx-release
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true
